# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.synced_folder "../", "/coyote"
  config.vm.network "forwarded_port", guest: 55672, host: 8080

  config.vm.provision :shell, inline: "sudo /coyote/dev/bootstrap.sh"
end
